In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('heartdisease.csv')
df.head()

   age  Gender  Family  diet  Lifestyle  cholestrol  heartdisease
0    0       0       1     1          3           0             1
1    0       1       1     1          3           0             1
2    1       0       0     0          2           1             1
3    4       0       1     1          3           2             0
4    3       1       1     0          0           2             0

In [3]:
df.shape

(500, 7)

In [4]:
df.isnull().sum()

age             0
Gender          0
Family          0
diet            0
Lifestyle       0
cholestrol      0
heartdisease    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           500 non-null    int64
 1   Gender        500 non-null    int64
 2   Family        500 non-null    int64
 3   diet          500 non-null    int64
 4   Lifestyle     500 non-null    int64
 5   cholestrol    500 non-null    int64
 6   heartdisease  500 non-null    int64
dtypes: int64(7)
memory usage: 27.5 KB

In [6]:
df.describe()

,age,Gender,Family,diet,Lifestyle,cholestrol,heartdisease
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,1.980000,0.472000,0.624000,0.992000,1.516000,1.026000,0.602000
std,1.469667,0.499715,0.484865,0.770144,1.025596,0.801629,0.489976
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,2.000000,0.000000,1.000000,1.000000,2.000000,1.000000,1.000000
75%,3.000000,1.000000,1.000000,2.000000,2.000000,2.000000,1.000000
max,4.000000,1.000000,1.000000,2.000000,3.000000,2.000000,1.000000

In [7]:
df.columns

Index(['age', 'Gender', 'Family', 'diet', 'Lifestyle', 'cholestrol',
       'heartdisease'],
      dtype='object')

In [8]:
!pip install pgmpy==1.0.0

Requirement already satisfied: pgmpy==1.0.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.0.0)
Requirement already satisfied: networkx in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (3.6.1)
Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (2.4.6)
Requirement already satisfied: scipy in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (1.17.1)
Requirement already satisfied: scikit-learn in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (1.9.0)
Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (2.3.3)
Requirement already satisfied: torch in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (2.13.0)
Requirement already satisfied: statsmodels in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (0.14.6)
Requirement already satisfied: tqdm in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (4.70.0)
Requirement already satisfied: joblib in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (1.5.3)
Requirement already satisfied: opt-einsum in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (3.4.0)
Requirement already satisfied: pyro-ppl in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pgmpy==1.0.0) (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->pgmpy==1.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->pgmpy==1.0.0) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas->pgmpy==1.0.0) (2026.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas->pgmpy==1.0.0) (1.17.0)
Requirement already satisfied: pyro-api>=0.1.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pyro-ppl->pgmpy==1.0.0) (0.1.2)
Requirement already satisfied: filelock in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch->pgmpy==1.0.0) (3.32.3)
Requirement already satisfied: typing-extensions>=4.10.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch->pgmpy==1.0.0) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch->pgmpy==1.0.0) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch->pgmpy==1.0.0) (1.14.0)
Requirement already satisfied: jinja2 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch->pgmpy==1.0.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch->pgmpy==1.0.0) (2026.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sympy>=1.13.3->torch->pgmpy==1.0.0) (1.3.0)
Requirement already satisfied: colorama in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tqdm->pgmpy==1.0.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from jinja2->torch->pgmpy==1.0.0) (3.0.3)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn->pgmpy==1.0.0) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn->pgmpy==1.0.0) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from statsmodels->pgmpy==1.0.0) (1.0.2)
Requirement already satisfied: packaging>=21.3 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from statsmodels->pgmpy==1.0.0) (26.3)

In [9]:
import pgmpy 
print(pgmpy.__version__)

1.0.0

In [10]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
model = DiscreteBayesianNetwork([
    ('age', 'heartdisease'), 
    ('Gender', 'heartdisease'), 
    ('Family', 'heartdisease'),
    ('diet', 'heartdisease'), 
    ('Lifestyle', 'heartdisease'),
    ('cholestrol', 'heartdisease') ])
mle = MaximumLikelihoodEstimator(model, df) 
cpds = mle.get_parameters() 
model.add_cpds(*cpds)
print(model.get_cpds('heartdisease'))

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'age': 'N', 'Gender': 'N', 'Family': 'N', 'diet': 'N', 'Lifestyle': 'N', 'cholestrol': 'N', 'heartdisease': 'N'}

+-----------------+---------------+---------------+-----+---------------+---------------+---------------+
| Family          | Family(0)     | Family(0)     | ... | Family(1)     | Family(1)     | Family(1)     |
+-----------------+---------------+---------------+-----+---------------+---------------+---------------+
| Gender          | Gender(0)     | Gender(0)     | ... | Gender(1)     | Gender(1)     | Gender(1)     |
+-----------------+---------------+---------------+-----+---------------+---------------+---------------+
| Lifestyle       | Lifestyle(0)  | Lifestyle(0)  | ... | Lifestyle(3)  | Lifestyle(3)  | Lifestyle(3)  |
+-----------------+---------------+---------------+-----+---------------+---------------+---------------+
| age             | age(0)        | age(0)        | ... | age(4)        | age(4)        | age(4)        |
+-----------------+---------------+---------------+-----+---------------+---------------+---------------+
| cholestrol      | cholestrol(0) | cholestrol(0) | ... | cholestrol(2) | cholestrol(2) | cholestrol(2) |
+-----------------+---------------+---------------+-----+---------------+---------------+---------------+
| diet            | diet(0)       | diet(1)       | ... | diet(0)       | diet(1)       | diet(2)       |
+-----------------+---------------+---------------+-----+---------------+---------------+---------------+
| heartdisease(0) | 0.5           | 0.5           | ... | 0.5           | 0.0           | 0.0           |
+-----------------+---------------+---------------+-----+---------------+---------------+---------------+
| heartdisease(1) | 0.5           | 0.5           | ... | 0.5           | 1.0           | 1.0           |
+-----------------+---------------+---------------+-----+---------------+---------------+---------------+

In [11]:
print(model.get_cpds('age'))

+--------+-------+
| age(0) | 0.23  |
+--------+-------+
| age(1) | 0.186 |
+--------+-------+
| age(2) | 0.17  |
+--------+-------+
| age(3) | 0.202 |
+--------+-------+
| age(4) | 0.212 |
+--------+-------+

In [12]:
print(model.get_cpds('Gender'))

+-----------+-------+
| Gender(0) | 0.528 |
+-----------+-------+
| Gender(1) | 0.472 |
+-----------+-------+

In [13]:
print(model.get_cpds('Family'))

+-----------+-------+
| Family(0) | 0.376 |
+-----------+-------+
| Family(1) | 0.624 |
+-----------+-------+